### PR TITLE
Chore upgrade ottoman

### PR DESCRIPTION
**Pull request by MiffyLiye**
issue: https://github.com/Wiredcraft/nestjs-boilerplate/issues/147

## breaking changes

* [JSCBC-1007](http://issues.couchbase.com/browse/JSCBC-1007): first_error_message/first_error_code are no longer available on error contexts
* Updates index naming to include the model's name
* If you were previously skipping certificate checking with the parameter `?ssl=no_verify` in your connection string, you'll need to update it to `?tls_verify=none`
* Custom port is not supported in connection string

### CODE REVIEW

**Review by xavierchow — APPROVED** [review]

**Comment by MiffyLiye** [comment]
@xavierchow can you help publish a major version release of `nestjs-ottoman` to npmjs.com

**Comment by xavierchow** [comment]
@MiffyLiye v2.0.0 is published.

**Comment by MiffyLiye** [comment]
@xavierchow the files in `dist` folder are not uploaded to npmjs.com in `v2.0.0`, you may need to publish a new patch version

**Comment by xavierchow** [comment]
hmm, I see, 
It's a fresh clone as I got a new laptop, I didn't run `yarn install`, so the prehook failed.
However it didn't block the publish.

```
 "prepublish": "yarn run build",
 ```

**Comment by xavierchow** [comment]
or, we should use `prepublishOnly` instead? @MiffyLiye 
https://docs.npmjs.com/cli/v9/using-npm/scripts

**Comment by MiffyLiye** [comment]
@xavierchow yes based on docs of recent npm versions
https://docs.npmjs.com/cli/v9/using-npm/scripts?v=true

## prepublish (DEPRECATED)

Does not run during npm publish, but does run during npm ci and npm install. See below for more info.
## prepublishOnly

Runs BEFORE the package is prepared and packed, ONLY on npm publish.

**Comment by xavierchow** [comment]
yes, I think we should use `prepublishOnly` for the building before the publish,
could you send a PR for it? thanks.

```
modified: package.json
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ package.json:20 @
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    >>>>"prepublish": "yarn run build",
    "prepublishOnly": "yarn run build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",


 ~/workspace/nestjs-ottoman  master !1  npm publish                                                                                                                                                                          ✔  14:53:53

> nestjs-ottoman@2.0.0 prepublishOnly
> yarn run build

yarn run v1.22.19
$ rimraf dist
/bin/sh: rimraf: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code 127
npm ERR! path /Users/xavzhou/workspace/nestjs-ottoman
npm ERR! command failed
npm ERR! command sh /var/folders/nk/tnxh9fv92flf3g6ygtqbsgfm0000gp/T/prepublishOnly-2999c0b7.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xavzhou/.npm/_logs/2023-01-04T06_53_57_984Z-debug-0.log
```

**Comment by MiffyLiye** [comment]
I will check which life cycle script is more suitable and create a PR.

### npm publish
These are run from the scripts
- prepublishOnly
- prepack
- prepare
- postpack
- publish
- postpublish

**Pull request merged**
